### ISSUE TITLE
Gitcoin - Create a new gas puzzle!

### ISSUE THREAD

**Issue by RareSkills** [RareSkills/gas-puzzles#21]
Contribute a new gas puzzle to the [RareSkills.io](https://RareSkills.io) repo. To qualify, your gas puzzle must:

* Follow the same pattern as the ones in this repo
* Inefficient code must be realistic and clean. The point is to teach developers how to make reasonable code great, not how to fix ugly code.
* The gas target must require using a non-obvious trick or two, but should not require excessive and highly advanced optimization, unless explicitly marked as such. (See ERC165 for an example)
* The problem should be realistic. Puzzles that are clearly useless like "discover if the calldata is a palindrome" won't be accepted.
* However, _solutions_ don't have to be safe or realistic. The point is to drill knowledge of the EVM.

For this bounty, **only one solution will be accepted.**

**Comment by Hendobox** [comment]
Might wanna check out my free contribution https://github.com/Hendobox/Rare-Skills-Gas-Puzzle
